language: node_js
node_js:
- node
sudo: required
services:
- docker
before_install:
- docker build -t lollolove/myapp-frontend-test:latest -f Dockerfile.dev .
script:
- docker run lollolove/myapp-frontend-test:latest npm run test -- --watchAll=false
deploy:
  provider: azure_web_apps
  username:
    secure: zf9s4KpVIFXmo3f1xAJ9fwU/lAqxpVsSzHREe9oMvJTzItrfszuhlA3aJurgd14JD/d4XTV9XAAKOqGGbm4F+oRilTvgy5s7vLqm6cEUUBG4f57cJAbTWe5iyEe+hYC5PrqunGZzale5raGqoBFQMWKhcgyRvNKUdsbXvmC8jKneBqseP69WQZJxVfzpMvGDeBYYdZE8dT21x0MpI7RT+r7UmRxs/oWQN0pnAXLr+eObPvS3S6erSYf7lwaSMy+yUbF21mopGXapeZcuhHN/fZWiCaNwO4C3oeOVXOZxm1LAne6lTqGAAiIqXQKMLALd+FvF38Jru3Al2efpL93LpBdFW9G1u25s/Qc2/s4rC4m1No7iXso1Bdcm2+1SclIP9AObQfvQ8qblNsVfPEXCMPLEudsWyJim976KCdZoy16z+jDsXnvAV+9pde3TrHREc8qBv1p4pVmKCfDmSLq02JVdwleQ9C8ALEQyIJ4yZwhCByPB9ytg3OZbAQw2e5ZkXngIoHhgEGeenryg1gTGyqESyHz65IM0Hv7jiw+mE9b+/waohFugoHDm2UZrlJ7+V+k21JJUOzzFWbH3qr536iywd245jQkPQQv+VPi74RgKnyUkYIYYhAwBz2M425msH2f+hyHfsyeX82dryWok/Tqsta04c97dKXtMNu/bkP0=
  password:
    secure: IZiyBrvQjyLqyWvP/MLwRODL+6b5KJjgMrBcHOfkCOdPR2wAE/OTHC/CLWk8u+JT/iweGqmQP1XO+MGiFCXKtVfpPx8s0iezue4hM/4H1RKNmF2Af80sowL891VT4L7AmXg70MfE/6JVvjH+2vb11mp5pEzFFA2vsI18FUI+ZHGg90/clJJ0QRYNBMQpM6tgn05n56spm2GW8SxlvldcCKo888OID1ysY8bXv+YE58UFCE+R7EATlh4HVr6VtE6UJcI3wc8k0BsLQ5WWytWRZMz2tUhdu0NNPL2ekvBAp31HOOG0MMxUx0s6GJXbfFQvG7McaGqU0bbmM9Vna7anyKHHzoDcD1bsH0EZ5K9OY4ps/MLdt0x3d8oMJPA+vyBrDf1gs3Y//i+TsBczwdp/JQwPZbCv8OYvCsbRTjuRuRkXnAu4emITbp8yvfJhppjNK+vfy/GcdiYamvr4SbsKSi91RNj68fLCcqwCS4Rq9prLTR7HHHiv5At7rh3X0hozy7YTY1gZRWV2ofmf2BFRQwr6cEaYY1tS36/eN2/DGn/5yYZGag9VcsTDXxzs2r9xVp7TKfgIJF/L/Wcus3CKJ0dJsNMAN2fdUD/yixO2q8OxcTYX9yUSzlru57thJ9QLJgJnfo4qxGK2nQinCPgTunFkD81U4dEntU1n+ODprA8=
  site: react-demo
  edge: true
