language: node_js
node_js:
  - node
sudo: required
services:
  - docker

before_install:
  - docker build -t lollolove/myapp-frontend-test:latest -f Dockerfile.dev .

script:
  - docker run lollolove/myapp-frontend-test:latest npm run test -- --coverage
