sudo: required
services:
  - docker

before_install:
  - docker build -t lollolove/myapp-frontend-test -f Dockerfile.dev .

script:
  - docker run myapp-frontend-test:latest npm run test -- --coverage
