language: node_js
node_js:
- node
sudo: required
services:
- docker
before_install:
- docker build -t lollolove/myapp-frontend-test:latest -f Dockerfile.dev .
script:
- docker run lollolove/myapp-frontend-test:latest npm run test -- --watchAll=false
deploy:
  provider: azure_web_apps
  username:
    secure: Z0ovssooOSOPpFn9fyq7tNTFC+RGGYtFBe6gMt+uvNnbtp6DoyX9+5WguKm7EiHle6stdMmDOAn/eFYQ/nMDFNEKvcxzlirC5qwdBeZXyFcaVNdtBggo8N4BqyxXpeHoEupbZ+Wn/o8C2cco6GFvfoYXisyApqX/eygtiUa0Xs/m1hCsvIjcUdSOL6psE8U0yChT/HUqva0ennFl3Be0EXx+71twK/PVBxLM9xfq5B6HpDkzzO4CWPbw9ZuecULcX3YlQ+FZpg4S2+kHO91+kBNHVlGOT4I5lESL/2eVnVqxyZptDj2LCW+ICFo/ykdVOzlIxRIcrpwe5JHPgxU2BcfzDSidM5eI+cp8D32dHsn0MUmgITjk/N+sw0rz0rR8+n8ICkmWNS+g7DdmxCiXh0oj9g+CX+18aOxfxysleP8nA0lJ0BVvuapyxuCyDL0B/+mddtEsh8vOOrUar/l8vhPgKVasCcOZm6a7vN8hltP3WYJTSkZVNC7HsFEcrRDexj80F19UtYS5dub5apaxEWJK2c/IEVO1I3xrTdRHNFNsXE42Is6+PyFzAtFQStJLXozR7vt6qztr/EYL0HlLy3fnlFbvQZHXxjZGKoIe96+gdu7swfeoxI2VgJ8wE0JcajqkwXrjALFt+DPrTt3x0bpQ55rikQdV/XQ6mc1djm8=
  password:
    secure: IZiyBrvQjyLqyWvP/MLwRODL+6b5KJjgMrBcHOfkCOdPR2wAE/OTHC/CLWk8u+JT/iweGqmQP1XO+MGiFCXKtVfpPx8s0iezue4hM/4H1RKNmF2Af80sowL891VT4L7AmXg70MfE/6JVvjH+2vb11mp5pEzFFA2vsI18FUI+ZHGg90/clJJ0QRYNBMQpM6tgn05n56spm2GW8SxlvldcCKo888OID1ysY8bXv+YE58UFCE+R7EATlh4HVr6VtE6UJcI3wc8k0BsLQ5WWytWRZMz2tUhdu0NNPL2ekvBAp31HOOG0MMxUx0s6GJXbfFQvG7McaGqU0bbmM9Vna7anyKHHzoDcD1bsH0EZ5K9OY4ps/MLdt0x3d8oMJPA+vyBrDf1gs3Y//i+TsBczwdp/JQwPZbCv8OYvCsbRTjuRuRkXnAu4emITbp8yvfJhppjNK+vfy/GcdiYamvr4SbsKSi91RNj68fLCcqwCS4Rq9prLTR7HHHiv5At7rh3X0hozy7YTY1gZRWV2ofmf2BFRQwr6cEaYY1tS36/eN2/DGn/5yYZGag9VcsTDXxzs2r9xVp7TKfgIJF/L/Wcus3CKJ0dJsNMAN2fdUD/yixO2q8OxcTYX9yUSzlru57thJ9QLJgJnfo4qxGK2nQinCPgTunFkD81U4dEntU1n+ODprA8=
  site: react-demo
  verbose: true
