version: '3'
services:
  myapp-frontend:
#    image: 'lollolove/myapp-frontend:1.0'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - '.:/srv/myapp-frontend'
    stdin_open: true
    tty: true
